assets:
  xml: RKOB_simplified_upper_with_marker.xml
  traj: traj_data/AJ026_Run_Comfortable.pkl

run:
  show_viewer: true
  # seconds: 3.0

task_enabled: true  #是否使用任务空间即xpos作为前馈项(当前支持site/body)
task_mode: site #site or body
task_names: ["CIAS", "R_TOE", "L_TOE", "R_HM5", "L_HM5", "HTOP"] # example of site names
# task_mode: body
# task_names: ["pelvis", "toes_r", "toes_l", "hand_r", "hand_l", "head"] #当使用body时指定需要跟踪的body name
use_orientation_task: true #是否使用orientation以及旋转角速度作为任务空间中的跟踪目标

kp_q: 100 # Kp for qpos
kd_q: 10 # Kd for qvel
kx: 500.0 # Kp for xpos
dx: 50.0 # Kd for xvel
kr: 200.0 # Kp for xmat (optional)
dr: 20.0 # Kd for angular velocity (optional)
torque_limit: 500.0 #每个关节qfrc applied的限值

# 用于优化任务的目标函数超参数
metrics: 
  wq: 1.0
  wx: 0.5
  wt: 1.0e-4
  task_error_agg: mean      # mean | rms | max
  # task_error_weights: [1, 1, 1, 1, 1, 1]  # 可按 task_names 顺序设权
  write_csv: true
  csv_path: metrics_baseline.csv
  plot: true
  scl_hint_percentile: 90

# RL 超参数定义
rl:
  seconds: 2.5            # episode length (sec)
  episodes: 50
  seed: 101
  action_stride: 5
  frac_step: 0.03
  gamma: 0.99
  init_std: 0.05
  lr: 1.0e-4
  ent_coef: 1.0e-4
  learn_std: true
  scales:                  
    EQ_SCL: 0.2
    EX_SCL: 0.1
    MT_SCL: 100.0
    TAU3_SCL: 500.0
  reward_weights:
    WQ: 1.0
    WX: 1.0
    WT: 1.0e-3
    WT3: 2.0
    WLIM: 1.0e-4
  gain_bounds:             
    lo: [0.2, 0.2, 0.2, 0.2]
    hi: [5.0, 5.0, 5.0, 5.0]
  phase_random: true 
  
eval:
  show_viewer: true
  policy_path: best_policy.npz
